---
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - devnet

  TaskApp-Web:
    image: taskmanager-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TaskApp-Web
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - devnet

networks:
  devnet:
    driver: bridge