name: Build and Contain ASP.NET Razor Pages Web Application

on:
  push:
    branches: 
      - master
      - develop
  
  pull_request:
    branches:
      - master

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line test workflows script
        run: echo "Hello GitHub Actions!"
