name: Build and Contain ASP.NET Razor Pages Web Application

on:
  push:
    branches: 
      - master
      - develop
  
  pull_request:
    branches:
      - master

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate image tag from commit
        id: vars
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          TAG="$COMMIT"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
         images: ongeziwe17/taskapp:${{ steps.vars }}
          
      - name: Docker Login to Hub Registry
        uses: docker/login-action@v3.4.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: docker.io
          # Username and password used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          # Buildx version. (eg. v0.3.0)
          version:  v0.3.0

      # - name: Scan image with Trivy
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: ongeziwe17/taskmanager-app:latest
      #     format: table
      #     exit-code: 1
      #     ignore-unfixed: true
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }} 
          
  # Clone TaskApp-Deploy and update the Docker tag in value.yam for Helm:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Setup Ubuntu for GitHub
  #       run: |
  #         git --version
  #         git config --global user.name "{{ secrets.Git_USER_NAME }}" 
  #         git config --global user.email "{{ secrets.Git_USER_EMAIL }}"
  #         git clone {{ secrets.TASKAPP_DEPLOY_REPOSITORY }}
  #         cd TaskApp-Deploy

  #         echo "Updating Docker tag in values.yaml..."
  #         sed -i "s/tag: .*/tag: $TAG/" values.yaml

  #         echo "Commit and push the change..."
  #         git add values.yaml
  #         git commit -m "Update Docker tag to $TAG"
  #         git push origin develop
          
