name: Build and Contain ASP.NET Razor Pages Web Application

on:
  push:
    branches: 
      - master
      - develop
  
  pull_request:
    branches:
      - master

env: 
  DOTNET_VERSION: '8.0'

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Application Packages and Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Docker compose build
        run: docker compose -f Docker-compose.yaml build --no-cache

      - name: Start Application Containers
        run: docker compose -f Docker-compose.yaml up -d

      - name: Wait time for SQL Server to be ready
        run:  |
          echo "Waiting for SQL Server to start..."
          sleep 20

      - name: Tear down containers
        if: always()
        run: docker compose -f Docker-compose.yaml down
